# Generated by Django 4.2.4 on 2024-12-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movieactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='eye_color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('hazel', 'Hazel')], max_length=5),
        ),
    ]
