# Generated by Django 4.2 on 2024-11-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
