# Generated by Django 4.2 on 2024-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hollymagazines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicatie',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
