# Generated by Django 4.2 on 2024-11-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hollymagazines', '0003_alter_publicatie_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicatie',
            options={'verbose_name_plural': 'Publicatii'},
        ),
        migrations.AlterModelOptions(
            name='revista',
            options={'verbose_name_plural': 'Reviste'},
        ),
    ]
